### ISSUE TITLE
using brushed DC with Raspberry Pi

### ISSUE THREAD

**Issue by CajKos** [Solo-FL/SoloPy#11]
Hi,

Short:
I would like to use the SoloUno together with my Raspberry Pi to control a brushed DC motor and control its speed.
**Will there be an example for this in the future? If not, how would I approach it best to parse the Arduino example?**

Long:
So far, the only example I found that comes close to this is [here](https://www.solomotorcontrollers.com/blog/control-speed-dc-motor-arduino-solo-closed-loop-sensorless/) where an Arduino is used and a potentiometer as input.
However I am using a raspberry pi and do not need a potentiometer. Looking at the code for brushless control I have seen that motor_type = 1 stands for BLDC_PMSM.
**Which number would then be for a brushed DC or where can I find the code documentation? Apart from that the functions would be the same for BLCD and brushed DC right? Only the Piano-Switch setting is different?**

Also:
When I started the SoloUno with Piano switches 1,2,4,5 Down my brushed DC starts to run immediately and continously. After trying out the brushless examples (I wanted to see what happens using them on the brushed DC). The motor stutters a lot and sometimes runs smoothly. I assume this depends on which of the 3 phases would be selected, since the brushed dc is only connected to 2. If I exit the example, the behaviour continues.
**So am I assuming right, that the last "action" is saved? Why does then the brushed dc automatically run if I switch on the SoloUno the first time?**

Thanks a lot!

**Comment by SOLO-Milad** [comment]
Hi @CajKos , 

For DC brushed Motors, you need to use **Motor Code 0** as the motor type ( check the [user manual of SOLO UNO](https://www.solomotorcontrollers.com/wp-content/uploads/materials/SOLO_UNO_User_Manual.pdf) and the piano switch settings)
so in the example code, you need to put "motor_type = 0 " to select this.
The main reason for this is you are going to operate in Digital mode ( sending data packets through UART), so you need to select the motor type also digitally ( Piano switch is useful once you are in analogue mode, again please read the Digital Vs Analogue control in the user manual of SOLO UNO and also in [UART and USB user manual](https://www.solomotorcontrollers.com/wp-content/uploads/materials/SOLO_UNO_Communication_Manual_UART_USB.pdf)).
All of the commands are extensively explained in SOLO UART and USB user manual [here](https://www.solomotorcontrollers.com/wp-content/uploads/materials/SOLO_UNO_Communication_Manual_UART_USB.pdf).

The reason that the Motor is keep rotating is you are not selecting the right motor type and the motor type 1 is for BLDC motors with 3 phases and they have a totally different topology of control and outputs, that's why the DC motor keeps rotating, I believe after setting the motor type at 0 the rest will be Ok, and the example codes will be very similar to the 3 phase motor with the same code flow ( setting the gains for Speed or Position and so on)
Once you set the Motor type once in Digital mode too, you don't need to set it again even after power recycling.
Please check these points and let us know if you succeed to run your system.
Milad

**Comment by SOLO-Milad** [comment]
Thanks @CajKos for the update and good job, let us know if you need anything else.
Milad
